/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j3c9JPmpkfC
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu"

export function Component() {
  return (
    <div className="grid min-h-screen w-full lg:grid-cols-[300px_1fr]">
      <div className="border-r bg-gray-100/40 dark:bg-gray-800/40">
        <div className="flex h-[60px] items-center border-b px-6">
          <Link className="flex items-center gap-2 font-semibold" href="#">
            <MapIcon className="h-6 w-6" />
            <span className="">Map</span>
          </Link>
        </div>
        <div className="flex-1 overflow-auto p-4">
          <div className="grid gap-4">
            <div className="flex items-center gap-2">
              <LayersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
              <h2 className="font-semibold text-lg">Layers</h2>
            </div>
            <div className="grid gap-2">
              <Label className="flex items-center" htmlFor="streets">
                <Input className="peer h-4 w-4" id="streets" type="checkbox" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Streets
                </span>
              </Label>
              <Label className="flex items-center" htmlFor="satellite">
                <Input
                  className="peer h-4 w-4"
                  id="satellite"
                  type="checkbox"
                />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Satellite
                </span>
              </Label>
              <Label className="flex items-center" htmlFor="traffic">
                <Input className="peer h-4 w-4" id="traffic" type="checkbox" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Traffic
                </span>
              </Label>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
              <h2 className="font-semibold text-lg">Points of interest</h2>
            </div>
            <div className="grid gap-2">
              <Label className="flex items-center" htmlFor="restaurants">
                <Input
                  className="peer h-4 w-4"
                  id="restaurants"
                  type="checkbox"
                />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Restaurants
                </span>
              </Label>
              <Label className="flex items-center" htmlFor="parks">
                <Input className="peer h-4 w-4" id="parks" type="checkbox" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Parks
                </span>
              </Label>
              <Label className="flex items-center" htmlFor="museums">
                <Input className="peer h-4 w-4" id="museums" type="checkbox" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Museums
                </span>
              </Label>
            </div>
            <div className="flex items-center gap-2">
              <LayersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
              <h2 className="font-semibold text-lg">Analytics</h2>
            </div>
            <div className="grid gap-2">
              <div className="flex items-center">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Population density
                </span>
                <span className="ml-auto text-sm peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  2500/mi²
                </span>
              </div>
              <div className="flex items-center">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Average income
                </span>
                <span className="ml-auto text-sm peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  $50,000
                </span>
              </div>
              <div className="flex items-center">
                <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span className="ml-2 peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  Tourist hotspots
                </span>
                <span className="ml-auto text-sm peer-disabled:opacity-50 dark:peer-disabled:opacity-70">
                  10
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function MapIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="3 6 9 3 15 6 21 3 21 18 15 21 9 18 3 21" />
      <line x1="9" x2="9" y1="3" y2="18" />
      <line x1="15" x2="15" y1="6" y2="21" />
    </svg>
  )
}

function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}

function LayersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 2 7 12 12 22 7 12 2" />
      <polyline points="2 17 12 22 22 17" />
      <polyline points="2 12 12 17 22 12" />
    </svg>
  )
}

function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}

function ChevronLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
